---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: looseleaf
# description will be included in the image's metadata
description: Looseleaf Bazzite KDE image with cosmetic branding only.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite
image-version: latest # latest is supported if you want new updates ASAP

# module configuration, executed in order
modules:
  # Keep Phase 1 changes isolated and easy to revert.
  - from-file: ../modules/cosmetic.yml
  - from-file: ../modules/software.yml

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
